//! Golden decoder tests against llvm-mc (P1.4, P1.5, P1.6).
//!
//! `tests/data/rv64_vectors.txt` is generated by `tools/gen-decoder-vectors.py`. For every
//! vector: decoding the 32-bit encoding must disassemble to exactly llvm-mc's canonical text,
//! and decoding the compressed encoding (when llvm-mc produced one) must yield the same
//! instruction as the 32-bit form.

use bridgev::isa::inst::{AluOp, AluWOp, Inst};
use bridgev::isa::{decode, decode_parts, disasm};

struct Vector {
    enc32: u32,
    enc16: Option<u16>,
    text: String,
}

fn vectors() -> Vec<Vector> {
    let data = include_str!("data/rv64_vectors.txt");
    data.lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .map(|l| {
            let mut it = l.splitn(3, ' ');
            let enc32 = u32::from_str_radix(it.next().unwrap(), 16).unwrap();
            let c = it.next().unwrap();
            let enc16 = (c != "----").then(|| u16::from_str_radix(c, 16).unwrap());
            Vector {
                enc32,
                enc16,
                text: it.next().unwrap().to_string(),
            }
        })
        .collect()
}

/// LLVM compresses some instructions to a different but equivalent encoding; normalize them:
/// * `add rd, rs, zero` and `addi rd, rs, 0` become `c.mv rd, rs` = `add rd, zero, rs`;
/// * `addiw rd, zero, imm` becomes `c.li rd, imm` = `addi rd, zero, imm` (0 + a 12-bit
///   immediate is the same in 32- and 64-bit arithmetic).
fn canon(i: Inst) -> Inst {
    match i {
        Inst::OpImmW {
            op: AluWOp::Addw,
            rd,
            rs1: 0,
            imm,
        } => Inst::OpImm {
            op: AluOp::Add,
            rd,
            rs1: 0,
            imm,
        },
        Inst::Op {
            op: AluOp::Add,
            rd,
            rs1,
            rs2: 0,
        }
        | Inst::OpImm {
            op: AluOp::Add,
            rd,
            rs1,
            imm: 0,
        } => Inst::Op {
            op: AluOp::Add,
            rd,
            rs1: 0,
            rs2: rs1,
        },
        other => other,
    }
}

#[test]
fn full_encodings_disassemble_like_llvm() {
    let vs = vectors();
    assert!(vs.len() > 1000, "vector file looks truncated: {}", vs.len());
    let mut failures = Vec::new();
    for v in &vs {
        let inst = decode(v.enc32);
        let got = disasm(&inst);
        if got != v.text {
            failures.push(format!(
                "{:08x}: expected `{}`, got `{got}` ({inst:?})",
                v.enc32, v.text
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{} mismatches:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn compressed_encodings_expand_to_full_form() {
    let mut failures = Vec::new();
    let mut n = 0;
    for v in vectors() {
        let Some(c) = v.enc16 else { continue };
        n += 1;
        let d =
            decode_parts::<()>(c, || unreachable!("compressed needs no second halfword")).unwrap();
        assert_eq!(d.len, 2);
        let full = decode(v.enc32);
        if canon(d.inst) != canon(full) {
            failures.push(format!(
                "{c:04x} vs {:08x} `{}`: {:?} != {:?}",
                v.enc32, v.text, d.inst, full
            ));
        }
    }
    assert!(n > 500, "too few compressed vectors: {n}");
    assert!(
        failures.is_empty(),
        "{} mismatches:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
